theme: jekyll-theme-minimal
title: Matt Branch UX Design: Student at University of Baltimore 
description: Information Architecture and Interaction Design student at University of Baltimore; portfolio of work. 
